name: release

on:
  push:
    tags:
      - "v*.*.*"

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install Pipewire
      run: |
        sudo add-apt-repository -y "deb http://archive.ubuntu.com/ubuntu `lsb_release -sc` main universe restricted multiverse"
        sudo apt-get update -y -qq
        sudo apt-get install libpipewire-0.3-dev
    - name: Build
      run: cargo build --release
    - name: Post-process
      run: |
        mkdir dist
        cp contrib/pipeswitchd.service dist
        strip target/release/pipeswitchd
        mv target/release/pipeswitchd dist
        cd dist
        zip pipeswitchd.zip *
        cd ../
        mv dist/pipeswitchd.zip pipeswitchd.zip
    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: pipeswitchd.zip
        path: pipeswitchd.zip
    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        files: pipeswitchd.zip